# 炉丝加热电压片选
furnace_wire_heating_select:
  voltage1: "00"
  voltage2: "00"
  voltage3: "00"
  voltage4: "00"

# 电压1设置
voltage1_settings:
  tail: "E900"

# 电压2设置
voltage2_settings:
  tail: "EA00"

# 电压3设置
voltage3_settings:
  tail: "EB00"

# 电压4设置
voltage4_settings:
  tail: "EC00"