# 在线监控判据类型
judge_type:
  type1: "0F0F0F0F" # 大于上限超限阈值为超限
  type2: "F0F0F0F0" # 小于下限超限阈值为超限
  type3: "FFFFFFFF" # 大于上限超限阈值，小于下限超限阈值为超限
  type4: "CCCCCCCC" # 小于上限超限阈值，大于下限超限阈值为超限

# 逻辑判断后续实现处理标识
process_identification:
  id1: "00CA" # 在载荷执行实验流程中满足逻辑判断条件，执行该批次后续动作
  id2: "00FC" # 满足条件执行其他实验流程（如待机、机构复位模式）

#判断后续处理
post_process:
  process1: "CA00"  # 执行该批次后续动作索引号
  process2: "FC00"  # 执行其他实验流程（如待机、机构复位模式）批次号
  process3: "0000"  # 按顺序执行